<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
    <head>
        <title>
            Beyond Exception Handling: Conditions and Restarts
        </title>
        <link rel="stylesheet" type="text/css" href="style.css">
    </head>
    <body>
        <h1>
            19. Beyond Exception Handling: Conditions and Restarts
        </h1>
        <p>
            One of Lisp's great features is its <i>condition</i> system. It serves a similar purpose to the exception handling systems in Java, Python, and C++ but is more flexible. In fact, its flexibility extends beyond error handling--conditions are more general than exceptions in that a condition can represent any occurrence during a program's execution that may be of interest to code at different levels on the call stack. For example, in the section "Other Uses for Conditions," you'll see that conditions can be used to emit warnings without disrupting execution of the code that emits the warning while allowing code higher on the call stack to control whether the warning message is printed. For the time being, however, I'll focus on error handling.
        </p>
        <p>
            The condition system is more flexible than exception systems because instead of providing a two-part division between the code that signals an error<sup>1</sup> and the code that handles it,<sup>2</sup> the condition system splits the responsibilities into three parts--<i>signaling</i> a condition, <i>handling</i> it, and <i>restarting</i>. In this chapter, I'll describe how you could use conditions in part of a hypothetical application for analyzing log files. You'll see how you could use the condition system to allow a low-level function to detect a problem while parsing a log file and signal an error, to allow mid-level code to provide several possible ways of recovering from such an error, and to allow code at the highest level of the application to define a policy for choosing which recovery strategy to use.
        </p>
        <p>
            To start, I'll introduce some terminology: <i>errors</i>, as I'll use the term, are the consequences of Murphy's law. If something can go wrong, it will: a file that your program needs to read will be missing, a disk that you need to write to will be full, the server you're talking to will crash, or the network will go down. If any of these things happen, it may stop a piece of code from doing what you want. But there's no bug; there's no place in the code that you can fix to make the nonexistent file exist or the disk not be full. However, if the rest of the program is depending on the actions that were going to be taken, then you'd better deal with the error somehow or you <i>will</i> have introduced a bug. So, errors aren't caused by bugs, but neglecting to handle an error is almost certainly a bug.
        </p>
        <p>
            So, what does it mean to handle an error? In a well-written program, each function is a black box hiding its inner workings. Programs are then built out of layers of functions: high-level functions are built on top of the lower-level functions, and so on. This hierarchy of functionality manifests itself at runtime in the form of the call stack: if <code>high</code> calls <code>medium</code>, which calls <code>low</code>, when the flow of control is in <code>low</code>, it's also still in <code>medium</code> and <code>high</code>, that is, they're still on the call stack.
        </p>
        <p>
            Because each function is a black box, function boundaries are an excellent place to deal with errors. Each function--<code>low</code>, for example--has a job to do. Its direct caller--<code>medium</code> in this case--is counting on it to do its job. However, an error that prevents it from doing its job puts all its callers at risk: <code>medium</code> called <code>low</code> because it needs the work done that <code>low</code> does; if that work doesn't get done, <code>medium</code> is in trouble. But this means that <code>medium</code>'s caller, <code>high</code>, is also in trouble--and so on up the call stack to the very top of the program. On the other hand, because each function is a black box, if any of the functions in the call stack can somehow do their job despite underlying errors, then none of the functions above it needs to know there was a problem--all those functions care about is that the function they called somehow did the work expected of it.
        </p>
        <p>
            In most languages, errors are handled by returning from a failing function and giving the caller the choice of either recovering or failing itself. Some languages use the normal function return mechanism, while languages with exceptions return control by <i>throwing</i> or <i>raising</i> an exception. Exceptions are a vast improvement over using normal function returns, but both schemes suffer from a common flaw: while searching for a function that can recover, the stack unwinds, which means code that might recover has to do so without the context of what the lower-level code was trying to do when the error actually occurred.
        </p>
        <p>
            Consider the hypothetical call chain of <code>high</code>, <code>medium</code>, <code>low</code>. If <code>low</code> fails and <code>medium</code> can't recover, the ball is in <code>high</code>'s court. For <code>high</code> to handle the error, it must either do its job without any help from <code>medium</code> or somehow change things so calling <code>medium</code> will work and call it again. The first option is theoretically clean but implies a lot of extra code--a whole extra implementation of whatever it was <code>medium</code> was supposed to do. And the further the stack unwinds, the more work that needs to be redone. The second option--patching things up and retrying--is tricky; for <code>high</code> to be able to change the state of the world so a second call into <code>medium</code> won't end up causing an error in <code>low</code>, it'd need an unseemly knowledge of the inner workings of both <code>medium</code> and <code>low</code>, contrary to the notion that each function is a black box.
        </p>
        <h2>
            <a name="the-lisp-way" id="the-lisp-way">The Lisp Way</a>
        </h2>
        <p>
            Common Lisp's error handling system gives you a way out of this conundrum by letting you separate the code that actually recovers from an error from the code that decides how to recover. Thus, you can put recovery code in low-level functions without committing to actually using any particular recovery strategy, leaving that decision to code in high-level functions.
        </p>
        <p>
            To get a sense of how this works, let's suppose you're writing an application that reads some sort of textual log file, such as a Web server's log. Somewhere in your application you'll have a function to parse the individual log entries. Let's assume you'll write a function, <code>parse-log-entry</code>, that will be passed a string containing the text of a single log entry and that is supposed to return a <code>log-entry</code> object representing the entry. This function will be called from a function, <code>parse-log-file</code>, that reads a complete log file and returns a list of objects representing all the entries in the file.
        </p>
        <p>
            To keep things simple, the <code>parse-log-entry</code> function will not be required to parse incorrectly formatted entries. It will, however, be able to detect when its input is malformed. But what should it do when it detects bad input? In C you'd return a special value to indicate there was a problem. In Java or Python you'd throw or raise an exception. In Common Lisp, you signal a condition.
        </p>
        <h2>
            <a name="conditions" id="conditions">Conditions</a>
        </h2>
        <p>
            A <i>condition</i> is an object whose class indicates the general nature of the condition and whose instance data carries information about the details of the particular circumstances that lead to the condition being signaled.<sup>3</sup> In this hypothetical log analysis program, you might define a condition class, <code>malformed-log-entry-error</code>, that <code>parse-log-entry</code> will signal if it's given data it can't parse.
        </p>
        <p>
            Condition classes are defined with the <code><b>DEFINE-CONDITION</b></code> macro, which works essentially the same as <code><b>DEFCLASS</b></code> except that the default superclass of classes defined with <code><b>DEFINE-CONDITION</b></code> is <code><b>CONDITION</b></code> rather than <code><b>STANDARD-OBJECT</b></code>. Slots are specified in the same way, and condition classes can singly and multiply inherit from other classes that descend from <code><b>CONDITION</b></code>. But for historical reasons, condition classes aren't required to be instances of <code><b>STANDARD-OBJECT</b></code>, so some of the functions you use with <code><b>DEFCLASS</b></code>ed classes aren't required to work with conditions. In particular, a condition's slots can't be accessed using <code><b>SLOT-VALUE</b></code>; you must specify either a <code>:reader</code> option or an <code>:accessor</code> option for any slot whose value you intend to use. Likewise, new condition objects are created with <code><b>MAKE-CONDITION</b></code> rather than <code><b>MAKE-INSTANCE</b></code>. <code><b>MAKE-CONDITION</b></code> initializes the slots of the new condition based on the <code>:initarg</code>s it's passed, but there's no way to further customize a condition's initialization, equivalent to <code><b>INITIALIZE-INSTANCE</b></code>.<sup>4</sup>
        </p>
        <p>
            When using the condition system for error handling, you should define your conditions as subclasses of <code><b>ERROR</b></code>, a subclass of <code><b>CONDITION</b></code>. Thus, you might define <code>malformed-log-entry-error</code>, with a slot to hold the argument that was passed to <code>parse-log-entry</code>, like this:
        </p>
        <pre>
(define-condition malformed-log-entry-error (error)
  ((text :initarg :text :reader text)))
</pre>
        <h2>
            <a name="condition-handlers" id="condition-handlers">Condition Handlers</a>
        </h2>
        <p>
            In <code>parse-log-entry</code> you'll signal a <code>malformed-log-entry-error</code> if you can't parse the log entry. You signal errors with the function <code><b>ERROR</b></code>, which calls the lower-level function <code><b>SIGNAL</b></code> and drops into the debugger if the condition isn't handled. You can call <code><b>ERROR</b></code> two ways: you can pass it an already instantiated condition object, or you can pass it the name of the condition class and any initargs needed to construct a new condition, and it will instantiate the condition for you. The former is occasionally useful for resignaling an existing condition object, but the latter is more concise. Thus, you could write <code>parse-log-entry</code> like this, eliding the details of actually parsing a log entry:
        </p>
        <pre>
(defun parse-log-entry (text)
  (if (well-formed-log-entry-p text)
    (make-instance 'log-entry ...)
    (error 'malformed-log-entry-error :text text)))
</pre>
        <p>
            What happens when the error is signaled depends on the code above <code>parse-log-entry</code> on the call stack. To avoid landing in the debugger, you must establish a <i>condition handler</i> in one of the functions leading to the call to <code>parse-log-entry</code>. When a condition is signaled, the signaling machinery looks through a list of active condition handlers, looking for a handler that can handle the condition being signaled based on the condition's class. Each condition handler consists of a type specifier indicating what types of conditions it can handle and a function that takes a single argument, the condition. At any given moment there can be many active condition handlers established at various levels of the call stack. When a condition is signaled, the signaling machinery finds the most recently established handler whose type specifier is compatible with the condition being signaled and calls its function, passing it the condition object.
        </p>
        <p>
            The handler function can then choose whether to handle the condition. The function can decline to handle the condition by simply returning normally, in which case control returns to the <code><b>SIGNAL</b></code> function, which will search for the next most recently established handler with a compatible type specifier. To handle the condition, the function must transfer control out of <code><b>SIGNAL</b></code> via a <i>nonlocal exit</i>. In the next section, you'll see how a handler can choose where to transfer control. However, many condition handlers simply want to unwind the stack to the place where they were established and then run some code. The macro <code><b>HANDLER-CASE</b></code> establishes this kind of condition handler. The basic form of a <code><b>HANDLER-CASE</b></code> is as follows:
        </p>
        <pre>
(handler-case <i>expression</i>
  <i>error-clause</i>*)
</pre>
        <p>
            where each <i>error-clause</i> is of the following form:
        </p>
        <pre>
(<i>condition-type</i> ([<i>var</i>]) <i>code</i>)
</pre>
        <p>
            If the <i>expression</i> returns normally, then its value is returned by the <code><b>HANDLER-CASE</b></code>. The body of a <code><b>HANDLER-CASE</b></code> must be a single expression; you can use <code><b>PROGN</b></code> to combine several expressions into a single form. If, however, the expression signals a condition that's an instance of any of the <i>condition-type</i>s specified in any <i>error-clause</i>, then the code in the appropriate error clause is executed and its value returned by the <code><b>HANDLER-CASE</b></code>. The <i>var</i>, if included, is the name of the variable that will hold the condition object when the handler code is executed. If the code doesn't need to access the condition object, you can omit the variable name.
        </p>
        <p>
            For instance, one way to handle the <code>malformed-log-entry-error</code> signaled by <code>parse-log-entry</code> in its caller, <code>parse-log-file</code>, would be to skip the malformed entry. In the following function, the <code><b>HANDLER-CASE</b></code> expression will either return the value returned by <code>parse-log-entry</code> or return <code><b>NIL</b></code> if a <code>malformed-log-entry-error</code> is signaled. (The <code>it</code> in the <code><b>LOOP</b></code> clause <code>collect it</code> is another <code><b>LOOP</b></code> keyword, which refers to the value of the most recently evaluated conditional test, in this case the value of <code>entry</code>.)
        </p>
        <pre>
(defun parse-log-file (file)
  (with-open-file (in file :direction :input)
    (loop for text = (read-line in nil nil) while text
       for entry = (handler-case (parse-log-entry text)
                     (malformed-log-entry-error () nil))
       when entry collect it)))
</pre>
        <p>
            When <code>parse-log-entry</code> returns normally, its value will be assigned to <code>entry</code> and collected by the <code><b>LOOP</b></code>. But if <code>parse-log-entry</code> signals a <code>malformed-log-entry-error</code>, then the error clause will return <code><b>NIL</b></code>, which won't be collected.
        </p>
        <div class="sidebarhead">
            JAVA-STYLE EXCEPTON HANDLING
        </div>
        <div class="sidebar">
            <p>
                <code><b>HANDLER-CASE</b></code> is the nearest analog in Common Lisp to Java- or Python-style exception handling. Where you might write this in Java:
            </p>
            <pre>
try {
  doStuff();
  doMoreStuff();
} catch (SomeException se) {
  recover(se);
}
</pre>
            <p>
                or this in Python:
            </p>
            <pre>
try:
  doStuff()
  doMoreStuff()
except SomeException, se:
  recover(se)
</pre>
            <p>
                in Common Lisp you'd write this:
            </p>
            <pre>
(handler-case
    (progn
      (do-stuff)
      (do-more-stuff))
  (some-exception (se) (recover se)))
</pre>
        </div>
        <p>
            This version of <code>parse-log-file</code> has one serious deficiency: it's doing too much. As its name suggests, the job of <code>parse-log-file</code> is to parse the file and produce a list of <code>log-entry</code> objects; if it can't, it's not its place to decide what to do instead. What if you want to use <code>parse-log-file</code> in an application that wants to tell the user that the log file is corrupted or one that wants to recover from malformed entries by fixing them up and re-parsing them? Or maybe an application is fine with skipping them but only until a certain number of corrupted entries have been seen.
        </p>
        <p>
            You could try to fix this problem by moving the <code><b>HANDLER-CASE</b></code> to a higher-level function. However, then you'd have no way to implement the current policy of skipping individual entries--when the error was signaled, the stack would be unwound all the way to the higher-level function, abandoning the parsing of the log file altogether. What you want is a way to provide the current recovery strategy without requiring that it always be used.
        </p>
        <h2>
            <a name="restarts" id="restarts">Restarts</a>
        </h2>
        <p>
            The condition system lets you do this by splitting the error handling code into two parts. You place code that actually recovers from errors into <i>restarts</i>, and condition handlers can then handle a condition by invoking an appropriate restart. You can place restart code in mid- or low-level functions, such as <code>parse-log-file</code> or <code>parse-log-entry</code>, while moving the condition handlers into the upper levels of the application.
        </p>
        <p>
            To change <code>parse-log-file</code> so it establishes a restart instead of a condition handler, you can change the <code><b>HANDLER-CASE</b></code> to a <code><b>RESTART-CASE</b></code>. The form of <code><b>RESTART-CASE</b></code> is quite similar to a <code><b>HANDLER-CASE</b></code> except the names of restarts are just names, not necessarily the names of condition types. In general, a restart name should describe the action the restart takes. In <code>parse-log-file</code>, you can call the restart <code>skip-log-entry</code> since that's what it does. The new version will look like this:
        </p>
        <pre>
(defun parse-log-file (file)
  (with-open-file (in file :direction :input)
    (loop for text = (read-line in nil nil) while text
       for entry = (restart-case (parse-log-entry text)
                     (skip-log-entry () nil))
       when entry collect it)))
</pre>
        <p>
            If you invoke this version of <code>parse-log-file</code> on a log file containing corrupted entries, it won't handle the error directly; you'll end up in the debugger. However, there among the various restarts presented by the debugger will be one called <code>skip-log-entry</code>, which, if you choose it, will cause <code>parse-log-file</code> to continue on its way as before. To avoid ending up in the debugger, you can establish a condition handler that invokes the <code>skip-log-entry</code> restart automatically.
        </p>
        <p>
            The advantage of establishing a restart rather than having <code>parse-log-file</code> handle the error directly is it makes <code>parse-log-file</code> usable in more situations. The higher-level code that invokes <code>parse-log-file</code> doesn't have to invoke the <code>skip-log-entry</code> restart. It can choose to handle the error at a higher level. Or, as I'll show in the next section, you can add restarts to <code>parse-log-entry</code> to provide other recovery strategies, and then condition handlers can choose which strategy they want to use.
        </p>
        <p>
            But before I can talk about that, you need to see how to set up a condition handler that will invoke the <code>skip-log-entry</code> restart. You can set up the handler anywhere in the chain of calls leading to <code>parse-log-file</code>. This may be quite high up in your application, not necessarily in <code>parse-log-file</code>'s direct caller. For instance, suppose the main entry point to your application is a function, <code>log-analyzer</code>, that finds a bunch of logs and analyzes them with the function <code>analyze-log</code>, which eventually leads to a call to <code>parse-log-file</code>. Without any error handling, it might look like this:
        </p>
        <pre>
(defun log-analyzer ()
  (dolist (log (find-all-logs))
    (analyze-log log)))
</pre>
        <p>
            The job of <code>analyze-log</code> is to call, directly or indirectly, <code>parse-log-file</code> and then do something with the list of log entries returned. An extremely simple version might look like this:
        </p>
        <pre>
(defun analyze-log (log)
  (dolist (entry (parse-log-file log))
    (analyze-entry entry)))
</pre>
        <p>
            where the function <code>analyze-entry</code> is presumably responsible for extracting whatever information you care about from each log entry and stashing it away somewhere.
        </p>
        <p>
            Thus, the path from the top-level function, <code>log-analyzer</code>, to <code>parse-log-entry</code>, which actually signals an error, is as follows:
        </p>
        <p>
            <img class="figure" src="figures/restart-call-stack.png">
        </p>
        <p>
            Assuming you always want to skip malformed log entries, you could change this function to establish a condition handler that invokes the <code>skip-log-entry</code> restart for you. However, you can't use <code><b>HANDLER-CASE</b></code> to establish the condition handler because then the stack would be unwound to the function where the <code><b>HANDLER-CASE</b></code> appears. Instead, you need to use the lower-level macro <code><b>HANDLER-BIND</b></code>. The basic form of <code><b>HANDLER-BIND</b></code> is as follows:
        </p>
        <pre>
(handler-bind (<i>binding</i>*) <i>form</i>*)
</pre>
        <p>
            where each binding is a list of a condition type and a handler function of one argument. After the handler bindings, the body of the <code><b>HANDLER-BIND</b></code> can contain any number of forms. Unlike the handler code in <code><b>HANDLER-CASE</b></code>, the handler code must be a function object, and it must accept a single argument. A more important difference between <code><b>HANDLER-BIND</b></code> and <code><b>HANDLER-CASE</b></code> is that the handler function bound by <code><b>HANDLER-BIND</b></code> will be run without unwinding the stack--the flow of control will still be in the call to <code>parse-log-entry</code> when this function is called. The call to <code><b>INVOKE-RESTART</b></code> will find and invoke the most recently bound restart with the given name. So you can add a handler to <code>log-analyzer</code> that will invoke the <code>skip-log-entry</code> restart established in <code>parse-log-file</code> like this:<sup>5</sup>
        </p>
        <pre>
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error
                  #'(lambda (c)
                      (invoke-restart 'skip-log-entry))))
    (dolist (log (find-all-logs))
      (analyze-log log))))
</pre>
        <p>
            In this <code><b>HANDLER-BIND</b></code>, the handler function is an anonymous function that invokes the restart <code>skip-log-entry</code>. You could also define a named function that does the same thing and bind it instead. In fact, a common practice when defining a restart is to define a function, with the same name and taking a single argument, the condition, that invokes the eponymous restart. Such functions are called <i>restart functions</i>. You could define a restart function for <code>skip-log-entry</code> like this:
        </p>
        <pre>
(defun skip-log-entry (c)
  (invoke-restart 'skip-log-entry))
</pre>
        <p>
            Then you could change the definition of <code>log-analyzer</code> to this:
        </p>
        <pre>
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error #'skip-log-entry))
    (dolist (log (find-all-logs))
      (analyze-log log))))
</pre>
        <p>
            As written, the <code>skip-log-entry</code> restart function assumes that a <code>skip-log-entry</code> restart has been established. If a <code>malformed-log-entry-error</code> is ever signaled by code called from <code>log-analyzer</code> without a <code>skip-log-entry</code> having been established, the call to <code><b>INVOKE-RESTART</b></code> will signal a <code><b>CONTROL-ERROR</b></code> when it fails to find the <code>skip-log-entry</code> restart. If you want to allow for the possibility that a <code>malformed-log-entry-error</code> might be signaled from code that doesn't have a <code>skip-log-entry</code> restart established, you could change the <code>skip-log-entry</code> function to this:
        </p>
        <pre>
(defun skip-log-entry (c)
  (let ((restart (find-restart 'skip-log-entry)))
    (when restart (invoke-restart restart))))
</pre>
        <p>
            <code><b>FIND-RESTART</b></code> looks for a restart with a given name and returns an object representing the restart if the restart is found and <code><b>NIL</b></code> if not. You can invoke the restart by passing the restart object to <code><b>INVOKE-RESTART</b></code>. Thus, when <code>skip-log-entry</code> is bound with <code><b>HANDLER-BIND</b></code>, it will handle the condition by invoking the <code>skip-log-entry</code> restart if one is available and otherwise will return normally, giving other condition handlers, bound higher on the stack, a chance to handle the condition.
        </p>
        <h2>
            <a name="providing-multiple-restarts" id="providing-multiple-restarts">Providing Multiple Restarts</a>
        </h2>
        <p>
            Since restarts must be explicitly invoked to have any effect, you can define multiple restarts, each providing a different recovery strategy. As I mentioned earlier, not all log-parsing applications will necessarily want to skip malformed entries. Some applications might want <code>parse-log-file</code> to include a special kind of object representing malformed entries in the list of <code>log-entry</code> objects; other applications may have some way to repair a malformed entry and may want a way to pass the fixed entry back to <code>parse-log-entry</code>.
        </p>
        <p>
            To allow more complex recovery protocols, restarts can take arbitrary arguments, which are passed in the call to <code><b>INVOKE-RESTART</b></code>. You can provide support for both the recovery strategies I just mentioned by adding two restarts to <code>parse-log-entry</code>, each of which takes a single argument. One simply returns the value it's passed as the return value of <code>parse-log-entry</code>, while the other tries to parse its argument in the place of the original log entry.
        </p>
        <pre>
(defun parse-log-entry (text)
  (if (well-formed-log-entry-p text)
    (make-instance 'log-entry ...)
    (restart-case (error 'malformed-log-entry-error :text text)
      (use-value (value) value)
      (reparse-entry (fixed-text) (parse-log-entry fixed-text)))))
</pre>
        <p>
            The name <code><b>USE-VALUE</b></code> is a standard name for this kind of restart. Common Lisp defines a restart function for <code><b>USE-VALUE</b></code> similar to the <code>skip-log-entry</code> function you just defined. So, if you wanted to change the policy on malformed entries to one that created an instance of <code>malformed-log-entry</code>, you could change <code>log-analyzer</code> to this (assuming the existence of a <code>malformed-log-entry</code> class with a <code>:text</code> initarg):
        </p>
        <pre>
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error
                  #'(lambda (c)
                      (use-value
                       (make-instance 'malformed-log-entry :text (text c))))))
    (dolist (log (find-all-logs))
      (analyze-log log))))
</pre>
        <p>
            You could also have put these new restarts into <code>parse-log-file</code> instead of <code>parse-log-entry</code>. However, you generally want to put restarts in the lowest-level code possible. It wouldn't, though, be appropriate to move the <code>skip-log-entry</code> restart into <code>parse-log-entry</code> since that would cause <code>parse-log-entry</code> to sometimes return normally with <code><b>NIL</b></code>, the very thing you started out trying to avoid. And it'd be an equally bad idea to remove the <code>skip-log-entry</code> restart on the theory that the condition handler could get the same effect by invoking the <code>use-value</code> restart with <code><b>NIL</b></code> as the argument; that would require the condition handler to have intimate knowledge of how the <code>parse-log-file</code> works. As it stands, the <code>skip-log-entry</code> is a properly abstracted part of the log-parsing API.
        </p>
        <h2>
            <a name="other-uses-for-conditions" id="other-uses-for-conditions">Other Uses for Conditions</a>
        </h2>
        <p>
            While conditions are mainly used for error handling, they can be used for other purposes--you can use conditions, condition handlers, and restarts to build a variety of protocols between low- and high-level code. The key to understanding the potential of conditions is to understand that merely signaling a condition has no effect on the flow of control.
        </p>
        <p>
            The primitive signaling function <code><b>SIGNAL</b></code> implements the mechanism of searching for an applicable condition handler and invoking its handler function. The reason a handler can decline to handle a condition by returning normally is because the call to the handler function is just a regular function call--when the handler returns, control passes back to <code><b>SIGNAL</b></code>, which then looks for another, less recently bound handler that can handle the condition. If <code><b>SIGNAL</b></code> runs out of condition handlers before the condition is handled, it also returns normally.
        </p>
        <p>
            The <code><b>ERROR</b></code> function you've been using calls <code><b>SIGNAL</b></code>. If the error is handled by a condition handler that transfers control via <code><b>HANDLER-CASE</b></code> or by invoking a restart, then the call to <code><b>SIGNAL</b></code> never returns. But if <code><b>SIGNAL</b></code> returns, <code><b>ERROR</b></code> invokes the debugger by calling the function stored in <code><b>*DEBUGGER-HOOK*</b></code>. Thus, a call to <code><b>ERROR</b></code> can never return normally; the condition must be handled either by a condition handler or in the debugger.
        </p>
        <p>
            Another condition signaling function, <code><b>WARN</b></code>, provides an example of a different kind of protocol built on the condition system. Like <code><b>ERROR</b></code>, <code><b>WARN</b></code> calls <code><b>SIGNAL</b></code> to signal a condition. But if <code><b>SIGNAL</b></code> returns, <code><b>WARN</b></code> doesn't invoke the debugger--it prints the condition to <code><b>*ERROR-OUTPUT*</b></code> and returns <code><b>NIL</b></code>, allowing its caller to proceed. <code><b>WARN</b></code> also establishes a restart, <code><b>MUFFLE-WARNING</b></code>, around the call to <code><b>SIGNAL</b></code> that can be used by a condition handler to make <code><b>WARN</b></code> return without printing anything. The restart function <code><b>MUFFLE-WARNING</b></code> finds and invokes its eponymous restart, signaling a <code><b>CONTROL-ERROR</b></code> if no such restart is available. Of course, a condition signaled with <code><b>WARN</b></code> could also be handled in some other way--a condition handler could "promote" a warning to an error by handling it as if it were an error.
        </p>
        <p>
            For instance, in the log-parsing application, if there were ways a log entry could be slightly malformed but still parsable, you could write <code>parse-log-entry</code> to go ahead and parse the slightly defective entries but to signal a condition with <code><b>WARN</b></code> when it did. Then the larger application could choose to let the warning print, to muffle the warning, or to treat the warning like an error, recovering the same way it would from a <code>malformed-log-entry-error</code>.
        </p>
        <p>
            A third error-signaling function, <code><b>CERROR</b></code>, provides yet another protocol. Like <code><b>ERROR</b></code>, <code><b>CERROR</b></code> will drop you into the debugger if the condition it signals isn't handled. But like <code><b>WARN</b></code>, it establishes a restart before it signals the condition. The restart, <code><b>CONTINUE</b></code>, causes <code><b>CERROR</b></code> to return normally--if the restart is invoked by a condition handler, it will keep you out of the debugger altogether. Otherwise, you can use the restart once you're in the debugger to resume the computation immediately after the call to <code><b>CERROR</b></code>. The function <code><b>CONTINUE</b></code> finds and invokes the <code><b>CONTINUE</b></code> restart if it's available and returns <code><b>NIL</b></code> otherwise.
        </p>
        <p>
            You can also build your own protocols on <code><b>SIGNAL</b></code>--whenever low-level code needs to communicate information back up the call stack to higher-level code, the condition mechanism is a reasonable mechanism to use. But for most purposes, one of the standard error or warning protocols should suffice.
        </p>
        <p>
            You'll use the condition system in future practical chapters, both for regular error handling and, in Chapter 25, to help in handling a tricky corner case of parsing ID3 files. Unfortunately, it's the fate of error handling to always get short shrift in programming texts--proper error handling, or lack thereof, is often the biggest difference between illustrative code and hardened, production-quality code. The trick to writing the latter has more to do with adopting a particularly rigorous way of thinking about software than with the details of any particular programming language constructs. That said, if your goal is to write that kind of software, you'll find the Common Lisp condition system is an excellent tool for writing robust code and one that fits quite nicely into Common Lisp's incremental development style.
        </p>
        <div class="sidebarhead">
            Writing Robust Software
        </div>
        <div class="sidebar">
            <p>
                For information on writing robust software, you could do worse than to start by finding a copy of <i>Software Reliability</i> (John Wiley &amp; Sons, 1976) by Glenford J. Meyers. Bertrand Meyer's writings on Design By Contract also provide a useful way of thinking about software correctness. For instance, see Chapters 11 and 12 of his <i>Object-Oriented Software Construction</i> (Prentice Hall, 1997). Keep in mind, however, that Bertrand Meyer is the inventor of Eiffel, a statically typed bondage and discipline language in the Algol/Ada school. While he has a lot of smart things to say about object orientation and software reliability, there's a fairly wide gap between his view of programming and The Lisp Way. Finally, for an excellent overview of the larger issues surrounding building fault-tolerant systems, see Chapter 3 of the classic <i>Transaction Processing: Concepts and Techniques</i> (Morgan Kaufmann, 1993) by Jim Gray and Andreas Reuter.
            </p>
        </div>
        <p>
            In the next chapter I'll give a quick overview of some of the 25 special operators you haven't had a chance to use yet, at least not directly.
        </p>
        <hr>
        <div class="notes">
            <p>
                <sup>1</sup><i>Throws</i> or <i>raises</i> an exception in Java/Python terms
            </p>
            <p>
                <sup>2</sup><i>Catches</i> the exception in Java/Python terms
            </p>
            <p>
                <sup>3</sup>In this respect, a condition is a lot like an exception in Java or Python except not all conditions represent an error or <i>exceptional</i> situation.
            </p>
            <p>
                <sup>4</sup>In some Common Lisp implementations, conditions are defined as subclasses of <code><b>STANDARD-OBJECT</b></code>, in which case <code><b>SLOT-VALUE</b></code>, <code><b>MAKE-INSTANCE</b></code>, and <code><b>INITIALIZE-INSTANCE</b></code> will work, but it's not portable to rely on it.
            </p>
            <p>
                <sup>5</sup>The compiler may complain if the parameter is never used. You can silence that warning by adding a declaration <code>(declare (ignore c))</code> as the first expression in the <code><b>LAMBDA</b></code> body.
            </p>
        </div>
        <div class="copyright">
            Copyright © 2003-2005, Peter Seibel
        </div>
    </body>
</html>
